config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'training_menus#index'
  resources :training_menus do
    resources :menu_records 
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form_level.rb
class FormLevel < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1: 完全に反動をつけて効かせることは殆ど、または全く意識しない。動作スピードも気にしない' },
    { id: 3, name: '2: 2と4の間。反動多少はつけてフォームは少し効かせ意識、スピードもあまり気にしない' },
    { id: 4, name: '3: 動作スピードはあまり意識しない、フォームは効かせ重視' },
    { id: 5, name: '4: 動作スピードをポジティブ1-4秒,ネガティブ2-5秒、フォームは最大限効かせ重視' }
  ]
  include ActiveHash::Associations
  has_many :menu_records
end

app/models/menu_record.rb
class MenuRecord < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :form_level
  belongs_to :training_menu

  validates :date, presence: true
  validates :form_level_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/muscle_category.rb
class MuscleCategory < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '背中' },
    { id: 3, name: '胸' },
    { id: 4, name: '脚' },
    { id: 5, name: '肩' },
    { id: 6, name: '2頭' },
    { id: 7, name: '3頭' },
    { id: 8, name: '腹筋' },
    { id: 9, name: '僧帽筋' },
    { id: 10, name: '全身、持久系' },
    { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :training_menus
end

app/models/training_menu.rb
class TrainingMenu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :muscle_category
  has_many :menu_records, dependent: :destroy
  has_many_attached :images
  belongs_to :user

  validates :name, :explanation, presence: true
  validates :muscle_category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :images, length: { maximum: 3, message: "画像は3枚以下にしてください" }

  def self.search(search)
    if search != ''
      TrainingMenu.where('name LIKE(?)', "%#{search}%")
    else
      TrainingMenu.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :training_menus
  has_many :menu_records

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/menu_records_controller.rb
class MenuRecordsController < ApplicationController
  before_action :set_training_menu, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_menu_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :move_to_index, except: :create

  def new
    @menu_record = MenuRecord.new
  end

  def create
    @menu_record = MenuRecord.new(menu_record_params)
    if @menu_record.save
      redirect_to training_menu_path(@training_menu.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @menu_record.update(menu_record_params)
      redirect_to training_menu_menu_record_path(@training_menu.id, @menu_record.id)
    else
      render :edit
    end
  end

  def destroy
    @menu_record.destroy
    redirect_to training_menu_path(@training_menu.id)
  end

  private

  def set_training_menu
    @training_menu = TrainingMenu.find(params[:training_menu_id])
  end

  def set_menu_record
    @menu_record = MenuRecord.find(params[:id])
  end

  def menu_record_params
    @training_menu = TrainingMenu.find(params[:training_menu_id])
    params.require(:menu_record).permit(:date, :form_level_id, :weight, :reps, :circuit_menus, :memo).merge(
      user_id: current_user.id, training_menu_id: @training_menu.id
    )
  end

  def move_to_index
    redirect_to root_path if user_signed_in? && current_user.id != @training_menu.user_id
  end
end

app/controllers/training_menus_controller.rb
class TrainingMenusController < ApplicationController
  before_action :set_item, except: [:index, :new, :create, :search]
  before_action :authenticate_user!, except: [:index]
  before_action :move_to_index, except: [:index, :new, :create, :search]

  def index
    @training_menus = TrainingMenu.all
  end

  def new
    @training_menu = TrainingMenu.new
  end

  def create
    @training_menu = TrainingMenu.new(training_menu_params)
    if @training_menu.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @menu_records = MenuRecord.where(training_menu_id: params[:id]).order('date DESC')

    weight_records = MenuRecord.where(training_menu_id: params[:id]).order('weight DESC')
    @max_weight = weight_records.first
    @max_weight_reps = weight_records.first
    @max_reps = @menu_records.maximum('reps')

    reps_records = MenuRecord.where(training_menu_id: params[:id]).order('reps DESC')
    @max_reps = reps_records.first
    @max_reps_weight = reps_records.first
  end

  def edit
  end

  def update
    if @training_menu.update(training_menu_params)
      redirect_to training_menu_path(@training_menu.id)
    else
      render :edit
    end
  end

  def destroy
    @training_menu.destroy
    redirect_to root_path
  end

  def search
    @training_menus = TrainingMenu.search(params[:keyword])
  end

  private

  def training_menu_params
    params.require(:training_menu).permit(:name, :explanation, :muscle_category_id, {images: []}).merge(user_id: current_user.id)
  end

  def set_item
    @training_menu = TrainingMenu.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if user_signed_in? && current_user.id != @training_menu.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_records_helper.rb
module MenuRecordsHelper
end

app/helpers/training_menus_helper.rb
module TrainingMenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTraining37792</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_records/edit.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="container">
    <h3><%= "#{@training_menu.name}の記録" %></h3>
    <%= render 'shared/error_messages', model: @menu_record %>
    <%= form_with(model: [@training_menu, @menu_record], local: true) do |form| %>
      日付
      <%= form.date_field :date %>
      フォームレベル
      <%= form.collection_select(:form_level_id, FormLevel.all, :id, :name, {}, {}) %>
      重量（kg）※半角数字で入力 ※両手で持った時の重量
      <%= form.text_field :weight %>
      回数（回）※半角数字で入力 ※.の後に続く回数はチーティングの回数
      <%= form.text_field :reps %>
      サーキットメニュー
      <%= form.text_field :circuit_menus %>
      メニューの説明、補足（※よく見るように）
      <%= form.text_area :memo %>
      <%= form.submit "更新する" %>
      <%=link_to 'トレーニングメニュー記録詳細ページもどる', training_menu_menu_record_path(@training_menu.id, @menu_record.id), class:"back-btn" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/menu_records/new.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="container">
    <h3><%= "#{@training_menu.name}の記録" %></h3>
    <%= render 'shared/error_messages', model: @menu_record %>
    <%= form_with(model: [@training_menu, @menu_record], local: true) do |form| %>
      日付
      <%= form.date_field :date %>
      フォームレベル
      <%= form.collection_select(:form_level_id, FormLevel.all, :id, :name, {}, {}) %>
      重量（kg）※半角数字で入力 ※両手で持った時の重量
      <%= form.text_field :weight %>
      回数（回）※半角数字で入力 ※.の後に続く回数はチーティングの回数
      <%= form.text_field :reps %>
      サーキットメニュー
      <%= form.text_field :circuit_menus %>
      メニューの説明、補足（※よく見るように）
      <%= form.text_area :memo %>
      <%= form.submit "記録する" %>
      <%=link_to 'トレーニングメニュー詳細ページもどる', training_menu_path(@training_menu), class:"back-btn" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/menu_records/show.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="content_post">
    <div class="more">
      <ul class="more_list">
        <li>
          <%= link_to '記録を編集', edit_training_menu_menu_record_path(@training_menu.id, @menu_record.id), method: :get %>
        </li>
        <li>
          <%= link_to '記録を削除', training_menu_menu_record_path(@training_menu.id, @menu_record.id), method: :delete, data: {confirm: "削除しますか？"} %>
        </li>
     </ul>
    </div>
    <div class="record_date">
      <div class="record_box">記録した日</div>
      <h2><%= @menu_record.date %></h2>
    </div>
    <div class="form_level">
      <div class="record_box">フォームレベル</div>
      <p><%= @menu_record.form_level.name %></p>
      <ul class="form_explanation">
        <h3>フォームレベル一覧</h3>
        <li>1: 完全に反動をつけて効かせることは殆ど、または全く意識しない。動作スピードも気にしない</li>
        <li>2: 2と4の間。反動多少はつけてフォームは少し効かせ意識、スピードもあまり気にしない</li>
        <li>3: 動作スピードはあまり意識しない、フォームは効かせ重視</li>
        <li>4: 動作スピードをポジティブ1-4秒,ネガティブ2-5秒、フォームは最大限効かせ重視</li>
      </ul>
    </div>
    <% unless @menu_record.weight == nil %>
      <div class="record_weight">
        <div class="record_box">重量</div>
        <h3><%= @menu_record.weight %>kg（両手）</h3>
      </div>
    <% end %>
    <% unless @menu_record.reps == nil %>
      <div class="record_reps">
        <div class="record_box">回数</div>
        <h3><%= @menu_record.reps %>回 ※.の後に続く回数はチーティングの回数</h3>
      </div>
    <% end %>
    <% unless @menu_record.circuit_menus == nil %>
      <div class="record_circuit_menus">
        <div class="record_box">サーキットメニュー</div>
        <h3><%= @menu_record.circuit_menus %></h3>
      </div>
    <% end %>
    <% unless @menu_record.memo == nil %>
      <div class="record_memo">
        <div class="record_box">メモ</div> 
        <h3><%= @menu_record.memo %></h3>
      </div>
    <% end %>
    
  </div>
  <%=link_to 'もどる', training_menu_path(@training_menu.id), class:"back-btn" %>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>
    Copyright PicTweet 2019.
  </p>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header__bar row">
    <h1 class="header-title"><%= link_to "My Training", root_path %></h1>
    <% if user_signed_in? %>
      <div class="user_nav grid-6">
        <span><%= current_user.nickname %>
        <ul class="user__info">
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
        </span>
      </div>
    <% else %>
    <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path, class: "post" %>
        <%= link_to "新規登録", new_user_registration_path, class: "post" %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_second_header.html.erb
<header class="header">
  <div class="header__bar row">
     <h1 class="header-title"><%= link_to "My Training", root_path %></h1>
    <div class="header_right"><%=link_to 'トップページへ戻る', root_path %><div>
  </div>
</header>

app/views/training_menus/edit.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="container">
    <h3>トレーニングメニューを編集する</h3>
    <%= render 'shared/error_messages', model: @training_menu %>
    <%= form_with(model: @training_menu, id: "training_menu", local: true) do |form| %>
      トレーニングメニューの名前
      <%= form.text_field :name%>
    <div class="img-upload">
      <div class="weight-bold-text">
        トレーニング画像
      </div>
      <div id="previews" class="preview-images"  ></div>
      <div class="click-upload">
        <%= form.file_field :images, name: 'training_menu[images][]',  data: {index: 0}%>
      </div>
    </div>
      鍛えられるところ
      <%= form.collection_select(:muscle_category_id, MuscleCategory.all, :id, :name, {}, {}) %>
      メニューの説明、補足
      <%= form.text_area :explanation, rows: "10" %>
      <%= form.submit "更新する" %>
      <%=link_to 'もどる',  training_menu_path(@training_menu.id), class:"back-btn" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>


    
      

app/views/training_menus/index.html.erb
<%= render "shared/header" %>
<% unless user_signed_in?  %>
  <div class="default_message">
    <h1>HELLO TRAINING</h1>
  </div>
<% end %>
<% if user_signed_in? %>
  <%= form_with(url: search_training_menus_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: " トレーニングメニューを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
<% end %>
<div class="contents row">
  <% @training_menus.each do |menu| %>
    <% if user_signed_in? && current_user.id == menu.user_id %>
      <div class="content">
        <div class="content_item" >メニュー名</div>
          <div class="content_detail"><%= menu.name%></div>
        <div class="content_item" >鍛えられる部位</div>
          <div class="content_detail"><%= menu.muscle_category.name%></div>
          <% if menu.images.attached? %>
            <%= image_tag menu.images[0] %>
          <% end %>
        <div class="content_item" >説明</div>
          <div class="content_detail"><%= menu.explanation %></div>
        <div class="more">
          <ul class="more_list">
            <li>
              <%= link_to '詳細へ', training_menu_path(menu.id), method: :get %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
</div>  
<% if user_signed_in? %>
  <%= link_to(new_training_menu_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>トレーニングメニューを投稿する</span>
    <%= image_tag 'icon_dumbbell.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<% end %>
<%= render "shared/footer" %>

app/views/training_menus/new.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="container">
    <h3>トレーニングメニューを登録する</h3>
    <%= render 'shared/error_messages', model: @training_menu %>
    <%= form_with(model: @training_menu, id: "training_menu",local: true) do |form| %>
      トレーニングメニューの名前
      <%= form.text_field :name%>
      <div class="img-upload">
        <div class="weight-bold-text">
          トレーニング画像
        </div>
        <div id="previews" class="preview-images"  ></div>
        <div class="click-upload">
          <%= form.file_field :images, name: 'training_menu[images][]', data: {index: 0}%>
        </div>
      </div>
      鍛えられるところ
      <%= form.collection_select(:muscle_category_id, MuscleCategory.all, :id, :name, {}, {}) %>
      メニューの説明、補足
      <%= form.text_area :explanation, rows: "10" %>
      <%= form.submit "登録する" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/training_menus/search.html.erb
<%= render "shared/second_header" %>
<%= form_with(url: search_training_menus_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "トレーニングメニューを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @training_menus.each do |menu| %>
    <div class="">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', training_menu_path(menu.id), method: :get %>
          </li>
        </ul>
      </div>
      <h2><%= menu.name%></h2>
      <p><%= menu.muscle_category.name%></p>
      <p><%= menu.explanation %></p>
      </span>
    </div>
  <% end %>
  <%=link_to 'トップページへもどる',  root_path, class:"back-btn" %>
</div>
<%= render "shared/footer" %>

app/views/training_menus/show.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="content_post">
    <div class="more">
      <ul class="more_list">
        <li>
          <%= link_to 'メニューを編集', edit_training_menu_path(@training_menu.id), method: :get %>
        </li>
        <li>
          <%= link_to 'メニューを削除', training_menu_path(@training_menu.id), method: :delete, data: {confirm: "削除しますか？"} %>
        </li>
     </ul>
    </div>
    <% if @training_menu.images.attached? %>
      <div class="menu_img">
        <div class="menu_block">参考画像</div>
        <%= image_tag @training_menu.images[0], class: 'menu-image'%> 
        <div class="other-images">
          <% @training_menu.images[1..-1].each do |image| %>
            <div class="other-image">
              <%= image_tag image %>
            </div>
          <%end%>
        </div>
      </div>
    <% end %>
    <div class="menu_name">
    <div class="menu_block">メニュー名</div>
    <h2><%= @training_menu.name %></h2>
    </div>
    <div class="menu_explanation">
    <div class="menu_block">解説等</div>
    <p><%= @training_menu.explanation %></p>
    </div>
    <span class="name"><%= @training_menu.muscle_category.name %>
    </span>
  </div>
  <div class="contents">
    
    <% unless  @max_weight == nil %>
        <h1 class="max-record"><%= "最高重量は#{@max_weight.weight}kg、その時の回数は#{@max_weight.reps}回" %></h1>
    <% end %>
    <% unless  @max_weight == nil %>
      <h1 class="max-record"><%= "最高回数は#{@max_reps.reps}回、その時の重量は#{@max_reps.weight}kg" %></h1>
    <% end %>
    
    <div class="contents row">
      <% @menu_records.each do |record| %>
        <div class="content">
          <div class="content_item">
            実施日
          </div>
          <div class="content_detail">
            <%= record.date%>
          </div>
          <% unless record.weight == nil %>
            <div class="content_item">
              重量
            </div>
            <div class="content_detail">
              <%= record.weight %>kg（両手）
            </div>
          <% end %>
          <% unless record.reps == nil %>
            <div class="content_item">
              回数
            </div>
            <div class="content_detail">
              <%= record.reps %>回 ※.の後に続く回数はチーティングの回数
            </div>
          <% end %>
          <div class="more">
            <ul class="more_list">
              <li>
                <%= link_to 'トレーニング記録詳細へ', training_menu_menu_record_path(@training_menu.id, record.id), method: :get %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
</div>
<%= link_to( new_training_menu_menu_record_path(@training_menu.id), class: 'purchase-btn') do %>
  <span class='purchase-btn-text'> <%= @training_menu.name %>の記録へ </span>
  <%= image_tag 'icon_dumbbell.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>